Algo/src/main/java/com/puercha/algo/user/controller/LoginController.java
Algo/src/main/java/com/puercha/algo/user/controller/UserController.java
Algo/src/main/java/com/puercha/algo/user/service/LoginManager.java
Algo/src/main/java/com/puercha/algo/user/service/LoginService.java
Algo/src/main/java/com/puercha/algo/user/service/UserManager.java
Algo/src/main/java/com/puercha/algo/user/service/UserService.java

LoginContoller 생성. LoginService 기능 정의, LoginManager작성. UserController생성,
UserManager 작성. UserService 기능 정의

feat: User 관련 서비스 기능 추가

---

Algo/src/main/java/com/puercha/algo/board/dao/PostingDAOImplXML.java
Algo/src/main/java/com/puercha/algo/board/vo/BoardPostVO.java
Algo/src/main/java/com/puercha/algo/challenge/vo/ChallengeResultVO.java
Algo/src/main/java/com/puercha/algo/common/FindCriteria.java
Algo/src/main/java/com/puercha/algo/learning/controller/LearningController.java
Algo/src/main/java/com/puercha/algo/learning/dao/LearningDAO.java
Algo/src/main/resources/mappers/PostingDAO-mapper.xml

processing_time -> processingTime
usingMemory -> usedMemory

style: challengeRsultVO 변수 수정

---

Algo/src/main/java/com/puercha/algo/learning/vo/SubjectVO.java

1/ SQL - SUBJECT
IMAGE_DATA
IMAGE_SIZE
IMAGE_TYPE
IMAGE_NAME

style: 변수 추가

---

Algo/src/main/java/com/puercha/algo/challenge/dao/ChallengeDAO.java
Algo/src/main/java/com/puercha/algo/challenge/dao/ChallengeDAOImpl.java
Algo/src/main/resources/config/database.properties
Algo/src/main/resources/mappers/ChallengeDAO-mapper.xml

구현한 것
- ChallengeDAO.java 인터페이스
- ChallengeDAOImpl.java 구현클래스
- ChallengeDAO-mapper.xml sql 매퍼

ChallengeDAO 구현

---

Algo/src/main/java/com/puercha/algo/common/Code.java
Algo/src/main/java/com/puercha/algo/user/controller/LoginController.java
Algo/src/main/java/com/puercha/algo/user/controller/UserController.java
Algo/src/main/java/com/puercha/algo/user/service/LoginManager.java
Algo/src/main/resources/mappers/UserDAO-mapper.xml

LoginController 작성, LoginManager 작성,
UserController 작성, UserManager 작성,
UserDAO-mapper.xml에 sql문 수정
Common패키지에 Code클래스 생성

feat: Login 및 User Controller추가

---

Algo/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Algo/src/main/webapp/WEB-INF/spring/root-context.xml

root-context, servlet-context 내용을 수정함

feat: context에 컴포넌트 추가

---

Algo/src/main/java/com/puercha/algo/user/vo/UserVO.java

style: gender type 수정

---

Algo/src/main/java/com/puercha/algo/user/dao/UserDAO.java
Algo/src/main/java/com/puercha/algo/user/dao/UserDAOImpl.java
Algo/src/main/resources/mappers/UserDAO-mapper.xml
Algo/src/test/java/com/puercha/algo/user/dao/UserDAOImplTest.java
Algo/src/test/java/com/puercha/algo/user/dao/UserManagerTest.java

UserDAOImplTest,UserManagerTest 추가함

test: UserDAOImpl, UserManager 테스트 코드 추가

---

Algo/pom.xml
Algo/src/main/java/com/puercha/algo/board/controller/BoardController.java
Algo/src/main/java/com/puercha/algo/board/dao/PostingDAO.java
Algo/src/main/java/com/puercha/algo/board/dao/PostingDAOImplXML.java
Algo/src/main/java/com/puercha/algo/board/service/BoardServiceImpl.java
Algo/src/main/java/com/puercha/algo/board/vo/AttachmentVO.java
Algo/src/main/java/com/puercha/algo/board/vo/BoardCategoryVO.java
Algo/src/main/java/com/puercha/algo/board/vo/BoardPostVO.java
Algo/src/main/resources/mappers/PostingDAO-mapper.xml
Algo/src/test/java/com/puercha/algo/board/dao/PostingDAOImplTest.java

PostingDAO junit test 구현하였습니다.
작동확인하였습니다.
몇몇 마이너한 오타/오류 수정하였습니다.

PostingDAO 테스트 코드 작성

---

Algo/src/main/webapp/WEB-INF/views/board/postView.jsp
Algo/src/main/webapp/WEB-INF/views/include/header.jsp
Algo/src/main/webapp/resources/common/css/common.css

feat: 게시판 상세보기 업데이트

---

Algo/src/main/java/com/puercha/algo/user/controller/LoginController.java
Algo/src/main/java/com/puercha/algo/user/vo/UserVO.java
Algo/src/main/resources/mappers/UserDAO-mapper.xml
Algo/src/test/java/com/puercha/algo/user/dao/UserManagerTest.java

LoginControlle , UserDAO-mapper,
UserManagerTest, UserVO 오타 수정

fix: UserDAO-mapper 등등 오타 수정

---

Algo/src/main/java/com/puercha/algo/board/controller/BoardController.java
Algo/src/main/java/com/puercha/algo/board/dao/PostingDAOImplXML.java
Algo/src/main/java/com/puercha/algo/board/service/BoardService.java
Algo/src/main/java/com/puercha/algo/board/service/BoardServiceImpl.java
Algo/src/main/resources/mappers/PostingDAO-mapper.xml
Algo/src/main/webapp/WEB-INF/views/board/board.jsp
Algo/src/main/webapp/WEB-INF/views/board/postView.jsp
Algo/src/main/webapp/WEB-INF/views/board/posting.jsp
Algo/src/test/java/com/puercha/algo/board/dao/PostingDAOImplTest.java

1/ 게시판 목록보기에 변수 추가했습니다.
2/ URLmapping 정책에 맞춰 boardController 수정하였습니다.
3/ boardMapper - 변수명 수정이 있었습니다.

feat: 게시판 목록보기

---

Algo/src/main/resources/mappers/PostingDAO-mapper.xml

style: 게시판목록 오류 수정

---

Algo/src/main/java/com/puercha/algo/user/controller/UserController.java
Algo/src/main/webapp/WEB-INF/views/user/profile.jsp
Algo/src/main/webapp/WEB-INF/views/user/signin.jsp
Algo/src/main/webapp/WEB-INF/views/user/signup.jsp

signin, signup, profile 작성
UserCotroller 수정함

feat: signiup 작성

---

Algo/src/main/java/com/puercha/algo/challenge/vo/ChallengeVO.java

username(출제자 이름, String) 필드 추가

feat: ChallengeVO 변경

---

Algo/src/main/java/com/puercha/algo/board/controller/BoardController.java
Algo/src/main/java/com/puercha/algo/challenge/controller/ChallengeController.java
Algo/src/main/java/com/puercha/algo/challenge/dao/ChallengeDAO.java
Algo/src/main/java/com/puercha/algo/challenge/dao/ChallengeDAOImpl.java
Algo/src/main/java/com/puercha/algo/challenge/service/ChallengeManager.java
Algo/src/main/java/com/puercha/algo/challenge/service/ChallengeService.java
Algo/src/main/java/com/puercha/algo/challenge/service/codelauncher/CaseFileManager.java
Algo/src/main/java/com/puercha/algo/challenge/service/codelauncher/CodeTester.java
Algo/src/main/java/com/puercha/algo/challenge/service/codelauncher/JavaCodeTester.java
Algo/src/main/java/com/puercha/algo/challenge/service/codelauncher/MemoryMonitor.java
Algo/src/main/java/com/puercha/algo/challenge/vo/ChallengeVO.java
Algo/src/main/java/com/puercha/algo/common/PageManager.java
Algo/src/main/java/com/puercha/algo/user/controller/LoginController.java
Algo/src/main/resources/mappers/ChallengeDAO-mapper.xml
Algo/src/main/webapp/WEB-INF/views/challenge/challengeList.jsp
Algo/src/main/webapp/WEB-INF/views/challenge/challengeSolving.jsp
Algo/src/main/webapp/WEB-INF/views/user/signin.jsp
Algo/src/test/java/com/puercha/algo/challenge/dao/ChallengeDAOImplTest.java
Algo/src/test/java/com/puercha/algo/challenge/service/MemoryMonitorTest.java

feat: 도전과제 기능 추가

---

Algo/src/main/java/com/puercha/algo/learning/controller/LearningController.java
Algo/src/main/java/com/puercha/algo/learning/dao/LearningDAO.java
Algo/src/main/java/com/puercha/algo/learning/dao/LearningDAOImpl.java
Algo/src/main/java/com/puercha/algo/learning/service/LearningManager.java
Algo/src/main/java/com/puercha/algo/learning/service/LearningService.java
Algo/src/main/resources/mappers/LearningDAO-mapper.xml
Algo/src/main/webapp/WEB-INF/views/learning/quiz.jsp
Algo/src/main/webapp/WEB-INF/views/learning/unitContent.jsp
Algo/src/test/java/com/puercha/algo/learning/dao/LearningDAOImplTest.java

feat: learning 마무리문제 읽기 구현

---

Algo/src/main/java/com/puercha/algo/board/controller/BoardController.java
Algo/src/main/java/com/puercha/algo/board/dao/PostingDAOImplXML.java
Algo/src/main/java/com/puercha/algo/board/service/BoardServiceImpl.java
Algo/src/main/resources/mappers/PostingDAO-mapper.xml
Algo/src/test/java/com/puercha/algo/board/dao/PostingDAOImplTest.java

style: 게시판 버그 수정

---

Algo/src/main/resources/mappers/LearningDAO-mapper.xml

subject의 created_at필드 오타난 것 수정함.

fix: 필드명 오타 수정

---

Algo/src/main/webapp/WEB-INF/views/admin/tutorApplicationList.jsp

feat: tutorApplicationList.jsp 추가
